### ISSUE TITLE
Haphazard Open Sourcing TODO list

### ISSUE THREAD

**Issue by jlouis** [shopgun/turtle#3]
To Open Source this application we need to:
- [x] Remove turtle_task and break a dependency on msgpack - in fact figure out why we have this in this repo at all.
- [x] Go through all the overrides. We probably don't want these for a release
- [x] Versioning updates - make sure we use versioning as expected
- [x] Introduce an official changelog so we can explain what happens in releases
- [x] Go over EDoc and make sure it builds correctly, and that we can generate documentation as expected
- [x] Publish package on hex.pm ?
- [x] We have lots of places where small updates can happen: child_spec helpers for instance.
- [x] Consider providing a callbackmod directly
